name: debugging
channels:
  - pytorch
  - conda-forge
dependencies:
  - anyio=4.3.0
  - aom=3.7.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - blas=2.121
  - blas-devel=3.9.0
  - bleach=6.1.0
  - blosc=1.21.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-blosc2=2.13.2
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - captum=0.7.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.13.1
  - fonttools=4.49.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.4
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=72.1
  - idna=3.6
  - imagecodecs=2023.9.18
  - imageio=2.34.0
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.2
  - intel-openmp=2024.0.0
  - ipykernel=6.29.3
  - ipython=8.22.1
  - ipywidgets=8.1.2
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - json5=0.9.17
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.3
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.1
  - jupyter_events=0.9.0
  - jupyter_server=2.12.5
  - jupyter_server_terminals=0.5.2
  - jupyterlab=4.1.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.3
  - jupyterlab_widgets=3.0.10
  - jxrlib=1.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lazy_loader=0.3
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.1.2
  - libavif=1.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=16.0.6
  - libclang13=16.0.6
  - libdeflate=1.19
  - libexpat=2.5.0
  - libffi=3.4.2
  - libglib=2.78.4
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libogg=1.3.4
  - libpng=1.6.43
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libtiff=4.6.0
  - libuv=1.47.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.5
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - lightning-utilities=0.10.1
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.5
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - mkl=2024.0.0
  - mkl-devel=2024.0.0
  - mkl-include=2024.0.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert=7.16.1
  - nbconvert-core=7.16.1
  - nbconvert-pandoc=7.16.1
  - nbformat=5.9.2
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook=7.1.1
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.2.1
  - overrides=7.7.0
  - packaging=23.2
  - pandoc=3.1.12.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.6
  - pcre2=10.42
  - pickleshare=0.7.5
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - ply=3.11
  - pot=0.9.3
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytorch=2.2.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywavelets=1.4.1
  - pywin32=306
  - pywinpty=2.0.13
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.8
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - rav1e=0.6.6
  - referencing=0.33.0
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.0
  - scikit-image=0.22.0
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.2
  - setuptools=69.1.1
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - svt-av1=1.7.0
  - sympy=1.12
  - tbb=2021.11.0
  - terminado=0.18.0
  - threadpoolctl=3.3.0
  - tifffile=2024.2.12
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - torchmetrics=1.2.1
  - torchvision=0.17.1
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.1
  - types-python-dateutil=2.8.19.20240106
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.2.1
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.42.0
  - widgetsnbextension=4.0.10
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.17.0
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - click==8.1.7
      - cocohelper==0.3.4
      - fsspec==2024.2.0
      - opencv-python==4.9.0.80
      - pandas==1.5.3
      - pillow==9.5.0
      - pycocotools==2.0.7
      - shapely==1.8.5.post1
      - zennit==0.5.1
